import {Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '700'],
  
});


export const metadata = {
  title: "softwarezon - Your Trusted Software Development Partner",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.svg", 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div><Navbar/>
        {children}</div>
      </body>
    </html>
  );
}
