import { Rubik } from "next/font/google";
import "./globals.css";
import UpperHeaderWrapper from "@/components/Wrapper/UpperHeaderWrapper";
import NavWrapper from "@/components/Wrapper/NavWrapper";
import FooterWrapper from "@/components/Wrapper/FooterWrapper";
import AOSWrapper from "@/components/shared/SlideInText/AOSWrapper";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "softwarezon - Your Trusted Software Development Partner",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <div className="flex flex-col min-h-screen bg-white">
          <UpperHeaderWrapper />
          <NavWrapper />
          <AOSWrapper />
          <main className="flex-grow">{children}</main>
          <FooterWrapper />
        </div>
      </body>
    </html>
  );
}
