import {Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar/Navbar";

const rubik = Rubik({
  subsets: ['latin'],  // বা প্রয়োজন অনুযায়ী
  weights: ['400', '700'],  // আপনি যে weight গুলো ব্যবহার করতে চান
  // optionally, variable: '--font-rubik'
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
